# Implements a limit of 5 requests per second for an IP address
limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=5r/s;

server {
    listen 80;
    server_name localhost;

    limit_req_status 429;

    # Root directory context for static web asset serving
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Intercept and throttle identity endpoints before they hit the backend application
        location /api/login {
            # Allows an instantaneous burst of 10 requests but
            # enforces the 5r/s rate with no synthetic delays
            limit_req zone=auth_limit burst=10 nodelay;

            proxy_pass http://backend-api:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/register {
            limit_req zone=auth_limit burst=10 nodelay;

            proxy_pass http://backend-api:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

    # Forwards health checks
    location /health {
            proxy_pass http://backend-api:5000/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

    # Catches and proxies data transactions
    location /api/ {
        # Points directly to the service container name designated in docker-compose.yml
        proxy_pass http://backend-api:5000;

        # Injects connection headers to preserve original client contexts
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}