# Defines isolated virtual routing zones to segment container communications.
networks:
  frontend-api:
    driver: bridge
  api-db:
    driver: bridge

services:
  # Installs the specified image in the current directory when called.
  installer:
    image: node:24-slim
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: sh
    command: -c "npm install"

  # Encapsulates the back-end relational data storage engine.
  postgres-db:
    image: postgres:18-alpine
    container_name: secure_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    # Mounts local provisioning schema definitions directly to the container lifecycle path.
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - api-db

  # Encapsulates the primary application routing and transaction logic.
  backend-api:
    build: ./backend
    container_name: secure_backend
    restart: always
    environment:
      DB_HOST: postgres-db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    networks:
      - frontend-api
      - api-db
    depends_on:
      - postgres-db

  # Encapsulates the front-end user presentation interface served via Nginx.
  frontend-ui:
    build: ./frontend
    container_name: secure_frontend
    restart: always
    ports:
      - "3000:80"
      - "3443:443"
    networks:
      - frontend-api

  # Encapsulates automated dynamic application security testing (DAST) within the network mesh.
  zap-scanner:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: pipeline_zap_scanner
    profiles:
      - pipeline-testing
    volumes:
      - .:/zap/wrk/:rw
    entrypoint: [ "zap-baseline.py" ]

    command: [
      "-t", "https://secure_frontend:443",
      "-z", "-config connection.ssl.signed=false",
      "-I",
      "-r", "dast_report.html"
    ]
    networks:
      - frontend-api
    depends_on:
      - frontend-ui