# ZAP baseline policy

10015	IGNORE	(Re-examine Cache-control Directives - Redundant for static authentication UI assets)
10049	IGNORE	(Storable and Cacheable Content - Caching static UI architecture is standard behavior)
10063	IGNORE	(Permissions Policy Header Not Set - Core authentication loop uses zero client hardware APIs)
10109	IGNORE	(Modern Web Application)
90004	IGNORE	(Cross-Origin-Embedder-Policy Header Missing or Invalid - COEP rules redundant for isolated host loopback)