# ZAP baseline policy

# Redundant for static authentication UI assets
10015	IGNORE	Re-examine Cache-control Directives

# Caching static UI architecture is standard behavior
10049	IGNORE	Storable and Cacheable Content

# Core authentication loop uses zero client hardware APIs)
10063	IGNORE	Permissions Policy Header Not Set

# This is an informational alert and so no changes are required
10109	IGNORE	Modern Web Application

# COEP rules redundant for isolated host loopback
90004	IGNORE	Cross-Origin-Embedder-Policy Header Missing or Invalid